controller_list:
  - name: fake_victor5_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint_gripper
  - name: fake_victor5_hand_controller
    joints:
      - joint_gripper